version: "3"
services:
  envoy:
    image: envoyproxy/envoy:v1.21.0
    ports:
      - "9901:9901"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
  grpc_server:
    image: my_grpc_service
    ports:
      - "50051:50051"
