services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - compnet

  gateway:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./gateway/Dockerfile-gateway
    image: ghcr.io/biosimulators/compose-gateway:0.0.10  # stable is 0.0.4
    container_name: gateway
    ports:
      - "3001:3001"
    networks:
      - compnet
    depends_on:
      - mongodb
    environment:
      - STANDALONE=False

  worker:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./worker/Dockerfile-worker
    image: ghcr.io/biosimulators/compose-worker:0.0.5  # stable is 0.0.2
    container_name: worker
    networks:
      - compnet
    depends_on:
      - mongodb

networks:
  compnet:
    driver: bridge