services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - compnet

  gateway:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./gateway/Dockerfile-gateway
    image: ghcr.io/biosimulators/compose-gateway:0.0.5  # stable is 0.0.4
    container_name: gateway
    networks:
      - compnet
    depends_on:
      - mongodb

  # worker:
  #   platform: linux/amd64
  #   build:
  #     context: .
  #     dockerfile: ./worker/Dockerfile-worker
  #   image: ghcr.io/biosimulators/compose-worker:0.0.1
  #   container_name: worker
  #   networks:
  #     - compnet
  #   depends_on:
  #     - mongodb

networks:
  compnet:
    driver: bridge