name: compose-server
channels:
  - readdy
  - conda-forge
dependencies:
  - pip
  # - python=3.10
  - poetry
  - pymem3dg
  # - readdy
  - pip:
      # - amici
      - cobra
      - copasi-basico
      - smoldyn
      # - tellurium
      - imageio
      - nbformat