# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: simulation.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'simulation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10simulation.proto\x12\nsimulation\x1a\x1cgoogle/protobuf/struct.proto\x1a\x19google/protobuf/any.proto\"-\n\x06Object\x12#\n\x05value\x18\x01 \x01(\x0b\x32\x14.google.protobuf.Any\"\x8c\x03\n\x07Process\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\x12/\n\x06\x63onfig\x18\x03 \x03(\x0b\x32\x1f.simulation.Process.ConfigEntry\x12/\n\x06inputs\x18\x04 \x03(\x0b\x32\x1f.simulation.Process.InputsEntry\x12\x31\n\x07outputs\x18\x05 \x03(\x0b\x32 .simulation.Process.OutputsEntry\x1a\x46\n\x0b\x43onfigEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct:\x02\x38\x01\x1a\x41\n\x0bInputsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12!\n\x05value\x18\x02 \x01(\x0b\x32\x12.simulation.Object:\x02\x38\x01\x1a\x42\n\x0cOutputsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12!\n\x05value\x18\x02 \x01(\x0b\x32\x12.simulation.Object:\x02\x38\x01\"z\n\x06Result\x12*\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x1c.simulation.Result.DataEntry\x1a\x44\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct:\x02\x38\x01\"+\n\x07Results\x12 \n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x12.simulation.Result\"\xd8\x01\n\x11SimulationRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x14\n\x0clast_updated\x18\x02 \x01(\t\x12\x12\n\nsimulators\x18\x03 \x03(\t\x12\x10\n\x08\x64uration\x18\x04 \x01(\x05\x12\x35\n\x04spec\x18\x05 \x03(\x0b\x32\'.simulation.SimulationRequest.SpecEntry\x1a@\n\tSpecEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\"\n\x05value\x18\x02 \x01(\x0b\x32\x13.simulation.Process:\x02\x38\x01\"^\n\x10SimulationUpdate\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x14\n\x0clast_updated\x18\x02 \x01(\t\x12$\n\x07results\x18\x03 \x01(\x0b\x32\x13.simulation.Results2f\n\x11SimulationService\x12Q\n\x10StreamSimulation\x12\x1d.simulation.SimulationRequest\x1a\x1c.simulation.SimulationUpdate0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'simulation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROCESS_CONFIGENTRY']._loaded_options = None
  _globals['_PROCESS_CONFIGENTRY']._serialized_options = b'8\001'
  _globals['_PROCESS_INPUTSENTRY']._loaded_options = None
  _globals['_PROCESS_INPUTSENTRY']._serialized_options = b'8\001'
  _globals['_PROCESS_OUTPUTSENTRY']._loaded_options = None
  _globals['_PROCESS_OUTPUTSENTRY']._serialized_options = b'8\001'
  _globals['_RESULT_DATAENTRY']._loaded_options = None
  _globals['_RESULT_DATAENTRY']._serialized_options = b'8\001'
  _globals['_SIMULATIONREQUEST_SPECENTRY']._loaded_options = None
  _globals['_SIMULATIONREQUEST_SPECENTRY']._serialized_options = b'8\001'
  _globals['_OBJECT']._serialized_start=89
  _globals['_OBJECT']._serialized_end=134
  _globals['_PROCESS']._serialized_start=137
  _globals['_PROCESS']._serialized_end=533
  _globals['_PROCESS_CONFIGENTRY']._serialized_start=328
  _globals['_PROCESS_CONFIGENTRY']._serialized_end=398
  _globals['_PROCESS_INPUTSENTRY']._serialized_start=400
  _globals['_PROCESS_INPUTSENTRY']._serialized_end=465
  _globals['_PROCESS_OUTPUTSENTRY']._serialized_start=467
  _globals['_PROCESS_OUTPUTSENTRY']._serialized_end=533
  _globals['_RESULT']._serialized_start=535
  _globals['_RESULT']._serialized_end=657
  _globals['_RESULT_DATAENTRY']._serialized_start=589
  _globals['_RESULT_DATAENTRY']._serialized_end=657
  _globals['_RESULTS']._serialized_start=659
  _globals['_RESULTS']._serialized_end=702
  _globals['_SIMULATIONREQUEST']._serialized_start=705
  _globals['_SIMULATIONREQUEST']._serialized_end=921
  _globals['_SIMULATIONREQUEST_SPECENTRY']._serialized_start=857
  _globals['_SIMULATIONREQUEST_SPECENTRY']._serialized_end=921
  _globals['_SIMULATIONUPDATE']._serialized_start=923
  _globals['_SIMULATIONUPDATE']._serialized_end=1017
  _globals['_SIMULATIONSERVICE']._serialized_start=1019
  _globals['_SIMULATIONSERVICE']._serialized_end=1121
# @@protoc_insertion_point(module_scope)
